name: main build

on:
  push:
    branches:
      - main

jobs:
  build_python_3_12:
    runs-on: ubuntu-latest
    steps:
# check out the github repository
    - uses: actions/checkout@v4.1.6
# set up python
    - name: set up python "3.12"
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.12"
# clean-up
    - name: clean up
      run: |
        rm -rf /home/runner/work/pycommons/pycommons/docs/build/
        rm -rf /home/runner/work/pycommons/pycommons/dist
        rm -rf /home/runner/work/pycommons/pycommons/build
# execute the actual make build process
    - name: execute the make build
      run: ./make.sh
# remove pycommons
    - name: purge local pycommons installation
      run: |
        pip uninstall -y pycommons
# attempt to install it again from github
    - name: install pycommons from github
      run: |
        pip install git+https://github.com/thomasWeise/pycommons.git
        python -c "import pycommons"
# fix urls in documentation
    - name: fix documentation urls
      run: |
        find /home/runner/work/pycommons/pycommons/docs/build/ \( -type d -name .git -prune \) -o -type f -name "*.html" -print0 | xargs -0 sed -i 's/ href=\"_static\// href=\"\/pycommons\/_static\//g'
        find /home/runner/work/pycommons/pycommons/docs/build/ \( -type d -name .git -prune \) -o -type f -name "*.html" -print0 | xargs -0 sed -i 's/ src=\"_static\// src=\"\/pycommons\/_static\//g'
        touch /home/runner/work/pycommons/pycommons/docs/build/.nojekyll
# deploy to github pages
    - name: deploy documentation
      uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e
      with:
        branch: gh-pages
        folder: /home/runner/work/pycommons/pycommons/docs/build/
        single-commit: true
